Repository idaho/hassio-trash-card, pull requests merged in 2023-12, with the labels that each got.

#120 Update release.yml
  .github/release.yml
Labels: ignore-for-release

#121 remove semantic-release because now using github release
  .releaserc.json
  package-lock.json
  package.json
Labels: ignore-for-release

#122 Update dependabot.yml
  .github/dependabot.yml
Labels: ignore-for-release

#126 Cleanup workflows
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/dependabot.yml
  .github/workflows/release.yaml
Labels: ignore-for-release

#136 configuration value added to control whether the label or the event summary should be used
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/sk.json
Labels: feature

#137 added configuration value to set the time from when a current day event should be hidden
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/sk.json
  src/utils/findActiveEvent.test.ts
  src/utils/findActiveEvent.ts
  src/utils/isTodayAfter.test.ts
  src/utils/isTodayAfter.ts
Labels: feature

#138 update README
  README.md
Labels: ignore-for-release

#139 Updated french translations
  src/translations/fr.json
Labels: translations

#140 Add option to set the date style
  README.md
  rollup.config.mjs
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/sk.json
  src/trashcard.ts
  src/utils/form/date-style.ts
  src/utils/form/ha-form.ts
  src/utils/form/ha-selector-date-style.ts
Labels: feature

#142 adjust icon colors - especially because of the icon color on a black background with a dark style
  src/cards/trash-card/trash-card.ts
Labels: fix

#144 Update french translation
  src/translations/fr.json
Labels: translations
