Repository idaho/hassio-trash-card, pull requests merged in 2024-10, with the labels that each got.

#409 Remove mushroom as dependency
  .github/ISSUE_TEMPLATE/feature.yaml
  .hass_dev/configuration.yaml
  README.md
  package-lock.json
  package.json
  rollup.config.mjs
  src/cards/trash-card/container/BaseContainerElement.ts
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/items/icon.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card-pattern-editor.ts
  src/cards/trash-card/trash-card.ts
  src/cards/trash-card/utils/migration.ts
  src/utils/defaultHaCardStyle.ts
  src/utils/form/ha-form.ts
  src/utils/ha.ts
Labels: feature

#410 Fix color contrast and picture scaling
  src/cards/trash-card/items/BaseItemElement.ts
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/items/chip.ts
  src/cards/trash-card/items/icon.ts
  src/utils/defaultHaCardStyle.ts
  src/utils/getColoredStyle.ts
Labels: bug

#412 don't show trash-card if no events are available
  src/cards/trash-card/container/cards.ts
  src/cards/trash-card/container/chips.ts
  src/cards/trash-card/container/icons.ts
  src/cards/trash-card/items/BaseItemElement.ts
  src/cards/trash-card/items/empty.ts
  src/cards/trash-card/trash-card.ts
  src/localize.ts
  src/translations/en.json
  src/utils/getColoredStyle.ts
Labels: feature

#415 Implement pattern matching type
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/trash-card-config.ts
  src/translations/en.json
  src/utils/eventsToItems.ts
  src/utils/itemSettings.ts
Labels: feature

#416 Add option to filter events by location
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/trash-card-config.ts
  src/translations/en.json
  src/utils/findActiveEvents.ts
  src/utils/getCalendarData.ts
Labels: feature

#417 Use browserlist to support older browsers
  package-lock.json
  package.json
  rollup.config.mjs
Labels: fix

#414 Update it.json
  src/translations/it.json
Labels: translations

#419 fix date time calculation caused by day light saving
  src/utils/getCalendarData.ts
  src/utils/normaliseEvents.test.ts
  src/utils/normaliseEvents.ts
Labels: fix

#420 option to use only all-day events
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/trash-card-config.ts
  src/translations/en.json
  src/utils/findActiveEvents.test.ts
  src/utils/findActiveEvents.ts
  src/utils/getCalendarData.ts
Labels: feature

#421 allow a minimum of 0 for config option next_days as a value
  src/cards/trash-card/formSchemas.ts
Labels: feature

#429 fix debugger card
  src/cards/trash-card/container/debug.ts
  src/cards/trash-card/trash-card.ts
Labels: fix

#433 Events were displayed as others although they should be excluded despite filter_events and pattern_exact
  src/utils/eventsToItems.ts
  src/utils/filterEventByPatterns.ts
  src/utils/findActiveEvents.ts
Labels: fix

#434 Update fr.json
  src/translations/fr.json
Labels: translations

#435 add czech translations
  src/localize.ts
  src/translations/cs.json
Labels: translations

#442 fix swedish language import
  src/localize.ts
  src/translations/sv.json
Labels: translations

#444 Add end date on card for multiday events
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/items/chip.ts
  src/cards/trash-card/items/icon.ts
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/sv.json
  src/utils/daysTill.test.ts
  src/utils/daysTill.ts
  src/utils/getDateString.ts
Labels: fix

#446 add Brazilian Portuguese translations
  src/cards/trash-card/trash-card.ts
  src/localize.ts
  src/translations/pt-br.json
Labels: translations

#449 Add end date on card for multiday events
  src/translations/fr.json
Labels: translations
