Repository idaho/hassio-trash-card, pull requests merged in 2024-03, with the labels that each got.

#243 days till calculation when event is not whole day event
  src/cards/trash-card/items/icon.ts
  src/utils/daysTill.test.ts
  src/utils/daysTill.ts
  src/utils/getDateString.ts
Labels: bug

#247 unnecessary re-renderings
  src/cards/trash-card/trash-card.ts
Labels: bug

#257 slovak translations typo
  src/translations/sk.json
Labels: translations

#259 Added Dutch translation
  src/localize.ts
  src/translations/nl.json
Labels: translations

#260 option to define custom date format
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/items/chip.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/nl.json
  src/translations/pl.json
  src/translations/sk.json
  src/utils/getDateString.ts
Labels: feature

#261 Fixed typo README.md
  README.md
Labels: ignore-for-release

#266 add danish translations
  src/localize.ts
  src/translations/da.json
Labels: translations

#275 fix refresh rate calculation
  src/cards/trash-card/trash-card.ts
Labels: fix

#276 timezone calculation half hours timezones
  src/utils/getTimeZoneOffset.test.ts
  src/utils/getTimeZoneOffset.ts
Labels: fix

#273 Make chips alignment configurable
  README.md
  src/cards/trash-card/container/chips.ts
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/nl.json
  src/translations/pl.json
  src/translations/sk.json
Labels: feature

#277 adding extra css identifier for today, tomorrow and another day
  src/cards/trash-card/container/cards.ts
  src/cards/trash-card/container/chips.ts
  src/cards/trash-card/container/icons.ts
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/items/chip.ts
  src/cards/trash-card/items/icon.ts
  src/utils/getDateString.ts
  src/utils/isDateToday.ts
  src/utils/isDateTomorrow.ts
Labels: feature
