Repository idaho/hassio-trash-card, pull requests merged in 2024-02, with the labels that each got.

#190 calculation of days till event
  src/cards/trash-card/trash-card.ts
Labels: fix

#198 add an issue template for translation requests
  .github/ISSUE_TEMPLATE/translation.yaml
Labels: ignore-for-release

#197 add hungarian translation
  src/localize.ts
  src/translations/hu.json
Labels: translations

#199 fix hungarian translation
  src/translations/hu.json
Labels: translations

#200 option to disable event grouping
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/sk.json
Labels: feature

#201 get multiple items from single event by pattern
  src/utils/eventsToItems.ts
Labels: fix

#208 add polish translations
  src/localize.ts
  src/translations/pl.json
Labels: translations

#210 refactor new eslint rules
  .eslintrc.json
  package-lock.json
  package.json
  src/cards/trash-card/const.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card-pattern-editor.ts
  src/cards/trash-card/trash-card.ts
  src/localize.ts
  src/trashcard.ts
  src/utils/computeDarkMode.ts
  src/utils/findActiveEvents.ts
  src/utils/form/date-style.ts
  src/utils/form/ha-form.ts
  src/utils/form/ha-selector-date-style.ts
  src/utils/normaliseEvents.test.ts
  src/utils/normaliseEvents.ts
Labels: ignore-for-release

#213 Implement color mode option
  README.md
  package-lock.json
  package.json
  src/cards/trash-card/elements/card.ts
  src/cards/trash-card/elements/chip.ts
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/localize.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/pl.json
  src/translations/sk.json
  src/trashcard.ts
  src/utils/form/card-style.ts
  src/utils/form/date-style.ts
  src/utils/form/ha-form.ts
  src/utils/form/ha-selector-card-style.ts
  src/utils/form/ha-selector-date-style.ts
Labels: feature

#214 Option to define refresh rate
  README.md
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/sk.json
  src/utils/form/defaultConfigStruct.ts
  src/utils/form/ha-form.ts
Labels: feature

#215 Setup for local development
  .gitignore
  .hass_dev/configuration.yaml
  .hass_dev/www/.gitkeep
  package.json
Labels: ignore-for-release

#216 Fix match always lower case
  src/utils/eventsToItems.ts
Labels: fix

#217 add missing translations in polish
  src/translations/pl.json
Labels: translations

#220 add debug mode option
  .github/ISSUE_TEMPLATE/bug.yaml
  README.md
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card.ts
Labels: feature

#222 fix formatting in timezone offset calculation if timezone offset between -1 and -10
  src/utils/getTimeZoneOffset.ts
Labels: fix

#223 create extra debug card to reduce complexity
  src/cards/trash-card/elements/debug.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card-pattern-editor.ts
  src/cards/trash-card/trash-card.ts
  src/utils/debugger.ts
  src/utils/defaultHaCardStyle.ts
  src/utils/fireEvent.ts
Labels: feature

#225 correct counter's key value
  src/translations/fr.json
Labels: translations

#230 fix hungarian translations typo
  src/translations/hu.json
Labels: translations

#226 refactoring components etc into smaller one
  package-lock.json
  package.json
  src/cards/trash-card/container/cards.ts
  src/cards/trash-card/container/chips.ts
  src/cards/trash-card/container/debug.ts
  src/cards/trash-card/container/index.ts
  src/cards/trash-card/elements/base.ts
  src/cards/trash-card/elements/card.ts
  src/cards/trash-card/elements/chip.ts
  src/cards/trash-card/elements/debug.ts
  src/cards/trash-card/elements/icon.ts
  src/cards/trash-card/elements/title.ts
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/items/chip.ts
  src/cards/trash-card/items/logrow.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/translations/fr.json
  src/translations/hu.json
  src/utils/debugger.ts
  src/utils/getCalendarData.ts
  src/utils/getColoredStyle.ts
  src/utils/getDateString.ts
  src/utils/getRgbColor.ts
  src/utils/normaliseEvents.test.ts
  src/utils/normaliseEvents.ts
Labels: refactor

#231 Implement availability for custom patterns
  src/cards/trash-card/container/cards.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card-pattern-editor.ts
  src/cards/trash-card/trash-card.ts
  src/cards/trash-card/utils/migration.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/pl.json
  src/translations/sk.json
  src/utils/calendarItem.ts
  src/utils/eventsToItems.ts
  src/utils/findActiveEvents.ts
  src/utils/getCalendarData.ts
  src/utils/itemSettings.ts
Labels: feature

#233 fix calculation of range end date to fetch calendar data
  src/cards/trash-card/trash-card.ts
Labels: fix

#234 icon size no applied
  src/cards/trash-card/items/icon.ts
Labels: fix

#235 create workflow to add a new version
  .github/workflows/version.yaml
Labels: ignore-for-release

#237 card update when changing language
  src/cards/trash-card/trash-card.ts
Labels: fix

#238 show pattern label on chip
  README.md
  src/cards/trash-card/formSchemas.ts
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/items/chip.ts
  src/cards/trash-card/trash-card-config.ts
  src/cards/trash-card/trash-card-editor.ts
  src/cards/trash-card/trash-card.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/pl.json
  src/translations/sk.json
Labels: feature

#239 Adjust badge size in icon style
  src/cards/trash-card/items/icon.ts
Labels: fix

#240 Add icon and image shape
  src/cards/trash-card/items/BaseItemElement.ts
  src/cards/trash-card/items/card.ts
  src/cards/trash-card/items/chip.ts
  src/cards/trash-card/items/icon.ts
Labels: feature
