Repository idaho/hassio-trash-card, pull requests merged in 2024-09, with the labels that each got.

#362 Updated English readme
  README.md
Labels: documentation

#396 add swedish translations
  src/localize.ts
  src/translations/se.json
Labels: translations

#405 Implement weekday as date presets and new custom date formatter
  package-lock.json
  package.json
  src/cards/trash-card/trash-card-config.ts
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/lv.json
  src/translations/nl.json
  src/translations/pl.json
  src/translations/se.json
  src/translations/sk.json
  src/translations/sl.json
  src/utils/getDateString.ts
Labels: feature

#407 add new default hassio config params to use visual editor in sections
  src/utils/form/defaultConfigStruct.ts
Labels: fix
